#!/usr/bin/env python3
"""
Template generators for power-steering output.

Generates continuation prompts and session summaries.
"""

from datetime import datetime
from typing import Dict, List

from ..models import CheckerResult, ConsiderationAnalysis


class ChecklistTemplate:
    """Generates formatted output for power-steering results."""

    def generate_continuation_prompt(self, analysis: ConsiderationAnalysis) -> str:
        """Generate actionable continuation prompt.

        Args:
            analysis: Analysis results with failed considerations

        Returns:
            Formatted continuation prompt
        """
        prompt_parts = [
            "POWER-STEERING: Session appears incomplete",
            "",
            "The following checks failed and need to be addressed:",
            "",
        ]

        # Group by category
        by_category = analysis.group_by_category()

        for category, failed in by_category.items():
            prompt_parts.append(f"**{category}**")
            for result in failed:
                prompt_parts.append(f"  - {result.reason}")
            prompt_parts.append("")

        prompt_parts.append("Once these are addressed, you may stop the session.")
        prompt_parts.append("")
        prompt_parts.append("To disable power-steering: export AMPLIHACK_SKIP_POWER_STEERING=1")

        return "\n".join(prompt_parts)

    def generate_summary(
        self,
        analysis: ConsiderationAnalysis,
        session_id: str,
        considerations: List[Dict],
    ) -> str:
        """Generate session summary for successful completion.

        Args:
            analysis: Analysis results
            session_id: Session identifier
            considerations: List of all considerations

        Returns:
            Formatted summary
        """
        summary_parts = [
            "# Power-Steering Session Summary",
            "",
            f"**Session ID**: {session_id}",
            f"**Completed**: {datetime.now().isoformat()}",
            "",
            "## Status",
            "All critical checks passed - session complete.",
            "",
            "## Considerations Verified",
        ]

        # List all satisfied checks
        for consideration in considerations:
            result = analysis.results.get(consideration["id"])
            if result and result.satisfied:
                summary_parts.append(f"- ✓ {consideration['question']}")

        summary_parts.append("")
        summary_parts.append("---")
        summary_parts.append("Generated by Power-Steering Mode (Phase 2)")

        return "\n".join(summary_parts)
