"""Pydantic models for workflow bricks.

Provides core data models for brick context, results, and status.
These models form the "studs" (public interface) that all bricks connect to.
"""

from __future__ import annotations

from datetime import UTC, datetime
from enum import Enum
from typing import TYPE_CHECKING, Any

from pydantic import BaseModel, Field, computed_field

if TYPE_CHECKING:
    pass


class BrickStatus(str, Enum):
    """Status of brick execution.

    Attributes:
        PENDING: Brick has not started execution
        SUCCESS: Brick completed successfully
        FAILED: Brick failed during execution
        SKIPPED: Brick was skipped (e.g., preconditions not met)
    """

    PENDING = "pending"
    SUCCESS = "success"
    FAILED = "failed"
    SKIPPED = "skipped"


class BrickContext(BaseModel):
    """Execution context passed to each brick.

    BrickContext carries all the information a brick needs to execute,
    including authentication, target repository, and shared metadata
    that passes between bricks in a workflow.

    Attributes:
        tenant_id: Azure tenant ID for telemetry isolation
        team_id: Engineering team identifier
        repo_owner: GitHub repository owner (user or org)
        repo_name: GitHub repository name
        branch_name: Target branch for operations
        actor: Identity performing the action (email or username)
        github_token: GitHub authentication token
        dry_run: If True, simulate without actual API calls
        metadata: Shared data passed between bricks in a workflow
        github_client: Optional pre-configured GitHub client

    Example:
        >>> context = BrickContext(
        ...     tenant_id="tenant-abc",
        ...     team_id="engineering-alpha",
        ...     repo_owner="my-org",
        ...     repo_name="my-repo",
        ...     branch_name="feat/new-feature",
        ...     actor="alice@example.com",
        ...     github_token="ghp_...",
        ... )
    """

    tenant_id: str = Field(..., description="Azure tenant ID for telemetry isolation")
    team_id: str = Field(..., description="Engineering team identifier")
    repo_owner: str = Field(..., description="GitHub repository owner")
    repo_name: str = Field(..., description="GitHub repository name")
    branch_name: str = Field(..., description="Target branch for operations")
    actor: str = Field(..., description="Identity performing the action")
    github_token: str = Field(..., description="GitHub authentication token")
    dry_run: bool = Field(default=False, description="Simulate without API calls")
    metadata: dict[str, Any] = Field(
        default_factory=dict,
        description="Shared data passed between bricks",
    )
    github_client: Any | None = Field(
        default=None,
        description="Pre-configured GitHub client",
        exclude=True,  # Don't serialize the client
    )

    model_config = {"arbitrary_types_allowed": True}

    @property
    def full_repo_name(self) -> str:
        """Get the full repository name (owner/repo)."""
        return f"{self.repo_owner}/{self.repo_name}"


class TelemetryEvent(BaseModel):
    """A telemetry event generated by a brick.

    Attributes:
        event_type: Type of event (e.g., "commit.created", "pr.opened")
        timestamp: When the event occurred
        actor: Who performed the action
        target: What the action was performed on
        details: Additional event-specific details
    """

    event_type: str = Field(..., description="Type of event")
    timestamp: datetime = Field(
        default_factory=lambda: datetime.now(UTC),
        description="When the event occurred",
    )
    actor: str = Field(..., description="Who performed the action")
    target: str = Field(..., description="What the action was performed on")
    details: dict[str, Any] = Field(
        default_factory=dict,
        description="Additional event details",
    )


class BrickResult(BaseModel):
    """Result from brick execution.

    BrickResult captures everything about a brick's execution including
    timing, outputs, and any errors that occurred.

    Attributes:
        status: Execution status (SUCCESS, FAILED, SKIPPED, PENDING)
        brick_name: Name of the brick that executed
        started_at: When execution started
        ended_at: When execution ended
        outputs: Dictionary of outputs (IDs, URLs, etc.)
        error: Error message if execution failed
        telemetry: List of generated telemetry events

    Example:
        >>> result = BrickResult(
        ...     status=BrickStatus.SUCCESS,
        ...     brick_name="CommitBrick",
        ...     started_at=datetime.now(timezone.utc),
        ...     ended_at=datetime.now(timezone.utc),
        ...     outputs={"commit_sha": "abc123"},
        ... )
        >>> print(result.duration_seconds)
        0
    """

    status: BrickStatus = Field(
        default=BrickStatus.PENDING,
        description="Execution status",
    )
    brick_name: str = Field(..., description="Name of the brick")
    started_at: datetime = Field(
        default_factory=lambda: datetime.now(UTC),
        description="Execution start time",
    )
    ended_at: datetime | None = Field(
        default=None,
        description="Execution end time",
    )
    outputs: dict[str, Any] = Field(
        default_factory=dict,
        description="Brick outputs",
    )
    error: str | None = Field(
        default=None,
        description="Error message if failed",
    )
    telemetry: list[TelemetryEvent] = Field(
        default_factory=list,
        description="Generated telemetry events",
    )

    @computed_field  # type: ignore[prop-decorator]
    @property
    def duration_seconds(self) -> int | None:
        """Calculate execution duration in seconds.

        Returns:
            Duration in seconds, or None if execution hasn't ended.
        """
        if self.ended_at is not None:
            return int((self.ended_at - self.started_at).total_seconds())
        return None

    def mark_success(self, outputs: dict[str, Any] | None = None) -> None:
        """Mark the result as successful.

        Args:
            outputs: Optional outputs to add to the result.
        """
        self.status = BrickStatus.SUCCESS
        self.ended_at = datetime.now(UTC)
        if outputs:
            self.outputs.update(outputs)

    def mark_failed(self, error: str) -> None:
        """Mark the result as failed.

        Args:
            error: Error message describing the failure.
        """
        self.status = BrickStatus.FAILED
        self.ended_at = datetime.now(UTC)
        self.error = error

    def mark_skipped(self, reason: str) -> None:
        """Mark the result as skipped.

        Args:
            reason: Reason why the brick was skipped.
        """
        self.status = BrickStatus.SKIPPED
        self.ended_at = datetime.now(UTC)
        self.error = reason

    def add_telemetry(
        self,
        event_type: str,
        actor: str,
        target: str,
        details: dict[str, Any] | None = None,
    ) -> None:
        """Add a telemetry event to the result.

        Args:
            event_type: Type of event
            actor: Who performed the action
            target: What the action was performed on
            details: Additional event details
        """
        event = TelemetryEvent(
            event_type=event_type,
            actor=actor,
            target=target,
            details=details or {},
        )
        self.telemetry.append(event)


__all__ = [
    "BrickStatus",
    "BrickContext",
    "BrickResult",
    "TelemetryEvent",
]
