"""M365 Telemetry Collection for Knowledge Worker Activity Framework.

This module provides telemetry collection and aggregation for Microsoft 365
activity data generated by knowledge workers.

Exports:
    - EmailEvidence: Dataclass for email telemetry
    - CalendarEvidence: Dataclass for calendar event telemetry
    - TeamsEvidence: Dataclass for Teams message telemetry
    - M365TelemetryCollector: Main telemetry collector class
"""

from azure_haymaker.knowledge_worker.telemetry.m365_telemetry import (
    CalendarEvidence,
    EmailEvidence,
    M365TelemetryCollector,
    TeamsEvidence,
)

__all__ = [
    "EmailEvidence",
    "CalendarEvidence",
    "TeamsEvidence",
    "M365TelemetryCollector",
]
